#!/bin/sh

# Put this file in /etc/cron.daily/ to reload the firewall
# to refresh ips resolutions
# Make sure this file is executable !

FIREWALL=/sbin/minifirewall

if [ -x "$FIREWALL" ] ; then
	$FIREWALL restart >/dev/null
fi

exit 0

